// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrHReikEM3Lq_3Cejg-iH1s0xNT6rlCMw',
    appId: '1:571382569162:web:ae8ab36dee50f59ae3bc33',
    messagingSenderId: '571382569162',
    projectId: 'e-commerce-app-3a668',
    authDomain: 'e-commerce-app-3a668.firebaseapp.com',
    storageBucket: 'e-commerce-app-3a668.appspot.com',
    measurementId: 'G-Z1JK3F9TZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9GqErQ907l9GHIDnpJrkqofD58GPTck',
    appId: '1:571382569162:android:497dc24cfb98bae8e3bc33',
    messagingSenderId: '571382569162',
    projectId: 'e-commerce-app-3a668',
    storageBucket: 'e-commerce-app-3a668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP31tHH8G63GswOBBSRxRdmkbI_tZnyb0',
    appId: '1:571382569162:ios:049f737cf578827de3bc33',
    messagingSenderId: '571382569162',
    projectId: 'e-commerce-app-3a668',
    storageBucket: 'e-commerce-app-3a668.appspot.com',
    iosBundleId: 'com.example.leafloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP31tHH8G63GswOBBSRxRdmkbI_tZnyb0',
    appId: '1:571382569162:ios:f8fb64ede6e7600ee3bc33',
    messagingSenderId: '571382569162',
    projectId: 'e-commerce-app-3a668',
    storageBucket: 'e-commerce-app-3a668.appspot.com',
    iosBundleId: 'com.example.leafloom.RunnerTests',
  );
}
